version: '3.8'

services:
  food-receipt-app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      # Persist database data
      - ./data:/app/data
      # Mount receipts.db to persist data
      - ./receipts.db:/app/receipts.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a simple web interface for database management
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=host.docker.internal
    depends_on:
      - food-receipt-app
    restart: unless-stopped
